import './styles/base.css';
import './styles/sidebar.css';
import './styles/components.css';
import './styles/theme.css';
import './styles/bsc.css';
import './styles/propostas.css';

import { initNavigation, navigate, applyFilter, clearFilter, renderAll, quickFilter, toggleQuickFilter, switchGestaoTab } from './navigation.js';
import { initAuth, doSignIn, doSignOut, toggleTheme } from './services/auth.js';
import { classify, exportOverrides } from './pages/review.js';
import { exportNoDatesCSV } from './pages/overview.js';
import { confirmDivergence, rejectDivergence } from './pages/divergences.js';
import { classifyFromProcv, setProcvFilter, setProcvSearch, exportProcvCSV } from './pages/procv.js';
import { undoFromClientes, setClientesFilter, setClientesSearch } from './pages/clientes.js';
import { setRankView } from './pages/ranking.js';
import { saveGoals, fmtGoalInput, rawGoalInput, fmtRoasInput } from './pages/goals-page.js';
import { renderBSC, importBSCFile, onBSCFileChange, enterTVMode, exitTVMode, initBSC, saveTVDurations } from './pages/bsc-page.js';
import { loadFile, processAll } from './pages/import-page.js';
import { setPropostasSearch, setPropostasStatus, setPropostasProduto, openExportModal, closeExportModal, doExportCSV, goToPropostasPage } from './pages/propostas.js';
import { clearState } from './core/storage.js';
import { toggleAccordion } from './utils/ui.js';

// Expose functions called from inline HTML handlers
window.navigate          = navigate;
window.applyFilter       = applyFilter;
window.clearFilter       = clearFilter;
window.quickFilter       = quickFilter;
window.toggleQuickFilter = toggleQuickFilter;
window.switchGestaoTab   = switchGestaoTab;
window.doSignIn          = doSignIn;
window.doSignOut         = doSignOut;
window.toggleTheme       = toggleTheme;
window.classify          = classify;
window.classifyFromProcv = classifyFromProcv;
window.setProcvFilter    = setProcvFilter;
window.setProcvSearch    = setProcvSearch;
window.exportProcvCSV    = exportProcvCSV;
window.exportOverrides   = exportOverrides;
window.exportNoDatesCSV  = exportNoDatesCSV;
window.confirmDivergence = confirmDivergence;
window.rejectDivergence  = rejectDivergence;
window.undoFromClientes  = undoFromClientes;
window.setClientesFilter = setClientesFilter;
window.setClientesSearch = setClientesSearch;
window.setRankView       = setRankView;
window.saveGoals         = saveGoals;
window.fmtGoalInput      = fmtGoalInput;
window.rawGoalInput      = rawGoalInput;
window.fmtRoasInput      = fmtRoasInput;
window.loadFile          = loadFile;
window.processAll        = processAll;
window.clearState          = clearState;
window.setPropostasSearch  = setPropostasSearch;
window.setPropostasStatus  = setPropostasStatus;
window.setPropostasProduto = setPropostasProduto;
window.openExportModal     = openExportModal;
window.closeExportModal    = closeExportModal;
window.doExportCSV         = doExportCSV;
window.goToPropostasPage   = goToPropostasPage;
window.toggleAccordion   = toggleAccordion;
window.renderBSC         = renderBSC;
window.importBSCFile     = importBSCFile;
window.onBSCFileChange   = onBSCFileChange;
window.enterTVMode       = enterTVMode;
window.exitTVMode        = exitTVMode;
window.saveTVDurations   = saveTVDurations;

initNavigation();
initAuth();
