import './styles/base.css';
import './styles/sidebar.css';
import './styles/components.css';
import './styles/theme.css';
import './styles/bsc.css';
import './styles/propostas.css';
import './styles/mobile.css';
import './styles/quitacoes.css';
import './styles/universidade.css';
import './styles/uni-admin.css';
import './styles/liberacao.css';

import { initNavigation, navigate, applyFilter, clearFilter, renderAll, quickFilter, toggleQuickFilter, switchGestaoTab, toggleSidebar, exitUniversidade, uniOpenCurso, uniGoBack, uniPlayAula, uniStartProva, uniVerCertificado, uniOpenAdmin, uniOpenGamificacao } from './navigation.js';
import { initAuth, doSignIn, doSignOut, toggleTheme } from './services/auth.js';
import { classify, exportOverrides } from './pages/review.js';
import { exportNoDatesCSV, exportNoValueCSV } from './pages/overview.js';
import { confirmDivergence, rejectDivergence } from './pages/divergences.js';
import { classifyFromProcv, setProcvFilter, setProcvSearch, exportProcvCSV, askClassify, sortProcv, toggleBatchSelect, selectAllBatch, clearBatchSelection, batchClassify } from './pages/procv.js';
import { undoFromClientes, setClientesFilter, setClientesSearch, askUndo, sortClientes } from './pages/clientes.js';
import { closeConfirm, doConfirm } from './utils/confirm.js';
import { setRankView } from './pages/ranking.js';
import { saveGoals, fmtGoalInput, rawGoalInput, fmtRoasInput, goalsNavMonth, goalsCopyPrev, goalsLoadPeriodo } from './pages/goals-page.js';
import { renderBSC, importBSCFile, onBSCFileChange, enterTVMode, exitTVMode, initBSC, saveTVDurations } from './pages/bsc-page.js';
import { loadFile, processAll } from './pages/import-page.js';
import { setPropostasSearch, setPropostasStatus, setPropostasProduto, setPropostasOrigem, setPropostasAudiencia, openExportModal, closeExportModal, doExportCSV, goToPropostasPage, sortPropostas } from './pages/propostas.js';
import { clearState } from './core/storage.js';
import { toggleAccordion } from './utils/ui.js';
import { openHistoryPanel, closeHistoryPanel } from './pages/history-panel.js';
import { keepSession } from './services/session-timeout.js';
import { closeBottomSheet, openBottomSheet } from './utils/mobile.js';
import { q_search, q_openModal, q_openEditModal, q_closeModal, q_save, q_showDetail, q_backToList, q_showComprovante, q_closeComprovante, q_attachDoc, q_toggleDev, q_onDocSelect, q_maskCPF, q_maskCNPJ, q_maskMoney } from './pages/quitacoes-page.js';
import { renderLiberacao, libAddCliente, libFecharModal, libCalcPreview, libSalvarCliente, libToggleOk, libSalvarAcerto, libSetSearch, libSetPreset, libClearDate, libSetDateManual, libVerMais, libImportarPlanilha, libOnImportFile, libDeletarCliente, libLimparBase } from './pages/liberacao-page.js';

// Expose functions called from inline HTML handlers
window.navigate          = navigate;
window.applyFilter       = applyFilter;
window.clearFilter       = clearFilter;
window.quickFilter       = quickFilter;
window.toggleQuickFilter = toggleQuickFilter;
window.switchGestaoTab   = switchGestaoTab;
window.toggleSidebar     = toggleSidebar;
window.doSignIn          = doSignIn;
window.doSignOut         = doSignOut;
window.toggleTheme       = toggleTheme;
window.classify          = classify;
window.classifyFromProcv = classifyFromProcv;
window.askClassify       = askClassify;
window.askUndo           = askUndo;
window.closeConfirm      = closeConfirm;
window.doConfirm         = doConfirm;
window.setProcvFilter    = setProcvFilter;
window.setProcvSearch    = setProcvSearch;
window.exportProcvCSV    = exportProcvCSV;
window.exportOverrides   = exportOverrides;
window.exportNoDatesCSV  = exportNoDatesCSV;
window.exportNoValueCSV  = exportNoValueCSV;
window.confirmDivergence = confirmDivergence;
window.rejectDivergence  = rejectDivergence;
window.undoFromClientes  = undoFromClientes;
window.setClientesFilter = setClientesFilter;
window.setClientesSearch = setClientesSearch;
window.setRankView       = setRankView;
window.saveGoals         = saveGoals;
window.fmtGoalInput      = fmtGoalInput;
window.rawGoalInput      = rawGoalInput;
window.fmtRoasInput      = fmtRoasInput;
window.goalsNavMonth     = goalsNavMonth;
window.goalsCopyPrev     = goalsCopyPrev;
window.goalsLoadPeriodo  = goalsLoadPeriodo;
window.loadFile          = loadFile;
window.processAll        = processAll;
window.clearState          = clearState;
window.setPropostasSearch  = setPropostasSearch;
window.setPropostasStatus  = setPropostasStatus;
window.setPropostasProduto  = setPropostasProduto;
window.setPropostasOrigem   = setPropostasOrigem;
window.setPropostasAudiencia = setPropostasAudiencia;
window.openExportModal     = openExportModal;
window.closeExportModal    = closeExportModal;
window.doExportCSV         = doExportCSV;
window.goToPropostasPage   = goToPropostasPage;
window.sortProcv           = sortProcv;
window.toggleBatchSelect   = toggleBatchSelect;
window.selectAllBatch      = selectAllBatch;
window.clearBatchSelection = clearBatchSelection;
window.batchClassify       = batchClassify;
window.sortClientes        = sortClientes;
window.sortPropostas       = sortPropostas;
window.libAddCliente       = libAddCliente;
window.libFecharModal      = libFecharModal;
window.libCalcPreview      = libCalcPreview;
window.libSalvarCliente    = libSalvarCliente;
window.libToggleOk         = libToggleOk;
window.libSalvarAcerto     = libSalvarAcerto;
window.libSetSearch        = libSetSearch;
window.libSetPreset        = libSetPreset;
window.libClearDate        = libClearDate;
window.libSetDateManual    = libSetDateManual;
window.libVerMais          = libVerMais;
window.libImportarPlanilha = libImportarPlanilha;
window.libOnImportFile     = libOnImportFile;
window.libDeletarCliente   = libDeletarCliente;
window.libLimparBase       = libLimparBase;
window.exitUniversidade    = exitUniversidade;
window.uniOpenCurso        = uniOpenCurso;
window.uniGoBack           = uniGoBack;
window.uniOpenAdmin        = uniOpenAdmin;
window.uniOpenGamificacao  = uniOpenGamificacao;
window.uniPlayAula        = uniPlayAula;
window.uniStartProva      = uniStartProva;
window.uniVerCertificado  = uniVerCertificado;
window.toggleAccordion   = toggleAccordion;
window.renderBSC         = renderBSC;
window.importBSCFile     = importBSCFile;
window.onBSCFileChange   = onBSCFileChange;
window.enterTVMode       = enterTVMode;
window.exitTVMode        = exitTVMode;
window.saveTVDurations   = saveTVDurations;
window.openHistoryPanel  = openHistoryPanel;
window.closeHistoryPanel = closeHistoryPanel;
window.keepSession        = keepSession;
window.closeBottomSheet   = closeBottomSheet;
window.openBottomSheet    = openBottomSheet;
window.q_search           = q_search;
window.q_openModal        = q_openModal;
window.q_openEditModal    = q_openEditModal;
window.q_closeModal       = q_closeModal;
window.q_save             = q_save;
window.q_showDetail       = q_showDetail;
window.q_backToList       = q_backToList;
window.q_showComprovante  = q_showComprovante;
window.q_closeComprovante = q_closeComprovante;
window.q_attachDoc        = q_attachDoc;
window.q_toggleDev        = q_toggleDev;
window.q_onDocSelect      = q_onDocSelect;
window.q_maskCPF          = q_maskCPF;
window.q_maskCNPJ         = q_maskCNPJ;
window.q_maskMoney        = q_maskMoney;

initNavigation();
initAuth();
